version: "3.8"
services:
    backend:
        container_name: backend
        image: golang:buster
        volumes: 
            - ./components/backend:/go/src/backend
        ports:
            - 4200:4200 # TODO: define me
        tty: true
        entrypoint: /bin/bash 

    db:
        container_name: db
        build:
            context: .
            dockerfile: Dockerfile.dbase
        env_file:
            - local.env
        restart: always

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
        - 8080:8080
