version: "3.8"
services:
    backend:
        container_name: backend
        image: golang:buster
        volumes: 
            - ./components/backend:/go/src/backend
        ports:
            - 4200:4200 # TODO: define me
        tty: true
        entrypoint: /bin/bash 

    db:
        # https://hub.docker.com/_/postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
