package main

// Generated by https://quicktype.io

type HousingPrices struct {
	ID                                   uint
	fld_sid                              string
	fld_id                               string
	fld_position                         string
	fld_created_at                       string
	fld_created_meta                     string
	fld_updated_at                       string
	fld_updated_meta                     string
	fld_meta                             string
	application_receipt_date             string
	application_completion_date          string
	location_of_property                 string
	zip_code                             string
	f8_hour_training_provider            string
	neighborhood                         string
	numofunits                           string
	ethnicity                            string
	hispanic_y_or_n                      string
	applicant_htfd_res                   string
	firsttimehomebuyer                   string
	household_size                       string
	house_hold_income_0_30_percent       string
	house_hold_income_31_50_percent      string
	house_hold_income_51_60_percent      string
	house_hold_income_61_80_percent      string
	house_hold_income_81_percent_or_more string
	purchase_price_total_dev_cost        string
	down_payment_amount                  string
	closing_cost_amount                  string
	total_amount_of_home_funds_comm      string
	closing_date1                        string
	closing_date2                        string
	closing_date3                        string
	volume1                              string
	page1                                string
	status1                              string
	volume2                              string
	page2                                string
	status2                              string
	volume3                              string
	page3                                string
	status3                              string
	fiscal_year                          string
	location                             string
	xcoord                               string
	ycoord                               string
	geom                                 string
	fld_computed_region_2vdc_22if        string
	fld_computed_region_35zh_8fi2        string
	fld_computed_region_ugzy_ysqh        string
	fld_computed_region_haf6_6xye        string
}
